//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_scratch.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public string InvoiceID { get; set; }
        public string TotalCost { get; set; }
        public string TotalSnacks { get; set; }
        public string Location { get; set; }
        public string DateAndTime { get; set; }
        public string Status { get; set; }
    }
}
